version: '3.4'

services:
  db:
     image: mysql:5.7
     environment:
       - MYSQL_DATABASES=dbgymclub
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_HOST=localhost
       - MYSQL_PORT=33306
       - MYSQL_USER=gymclubuser
       - MYSQL_PASSWORD=root
       - MYSQL_MY_DATABASE=dbgymclub
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always
     ports:
       - "3306:3306"
     networks:
       - backend
  api:
    depends_on:
       - db
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5556
    ports:
       - "5556:5556"
    networks:
      - backend

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
       - "8520:80"
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
    dbdata:


  

