version: '3.4'

services:
  db_server:
    container_name: db_server
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - '.:/repo'
      - 'data-volume:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    working_dir: /repo
    networks:
      - backend
  

  gymclub:
    build:
      context: .
      dockerfile: ui/Dockerfile
    networks:
      - backend
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:80;
    ports:
     - "5204:80"
     - "5254:443"

networks:
  backend:
    driver: bridge
volumes:
  data-volume:


  


