version: '3.4'

services:
  db_server:
    container_name: db_server
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - '.:/repo'
      - 'data-volume:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    working_dir: /repo
    networks:
      - backend
  api:
    depends_on:
       - db_server
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5556
    ports:
       - "5556:5556"
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  data-volume:


  

