version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: api/Dockerfile

  ui:
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: ui/Dockerfile


  

